// <auto-generated />
namespace OnlineLibraryMVCApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_DateAdded_toBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_DateAdded_toBook));
        
        string IMigrationMetadata.Id
        {
            get { return "202001280745384_Added_DateAdded_toBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
