// <auto-generated />
namespace OnlineLibraryMVCApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Removed_KEY_ISBN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removed_KEY_ISBN));
        
        string IMigrationMetadata.Id
        {
            get { return "202002020743270_Removed_KEY_ISBN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
